In [9]:
import numpy as np
import tensorflow as tf
tf.__version__

'2.8.0'

In [10]:
from keras.layers import Dense
from keras.models import Sequential
X = np.array([[0,0], [0,1], [1,0], [1,1]])
y = np.array([0,1,1,1])
print(X)
print(X.shape)
print(y)

[[0 0]
 [0 1]
 [1 0]
 [1 1]]
(4, 2)
[0 1 1 1]


In [11]:
# Multilayer Perceptron

model = Sequential()
model.add(Dense(2, input_shape=(2,)))

# Designing Model Architecture
model.add(Dense(1, activation='sigmoid'))
model.compile(optimizer='adam', loss='mse', metrics='mean_squared_error')
model.output_shape

(None, 1)

In [12]:
history = model.fit(X, y, epochs=200, batch_size=1)

Epoch 1/200


2022-05-19 14:20:45.851793: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.


4/4 [==============================] - 2s 7ms/step - loss: 0.1773 - mean_squared_error: 0.1773
Epoch 2/200
4/4 [==============================] - 0s 8ms/step - loss: 0.1747 - mean_squared_error: 0.1747
Epoch 3/200
4/4 [==============================] - 0s 7ms/step - loss: 0.1737 - mean_squared_error: 0.1737
Epoch 4/200
4/4 [==============================] - 0s 8ms/step - loss: 0.1717 - mean_squared_error: 0.1717
Epoch 5/200
4/4 [==============================] - 0s 8ms/step - loss: 0.1706 - mean_squared_error: 0.1706
Epoch 6/200
4/4 [==============================] - 0s 9ms/step - loss: 0.1693 - mean_squared_error: 0.1693
Epoch 7/200
4/4 [==============================] - 0s 8ms/step - loss: 0.1679 - mean_squared_error: 0.1679
Epoch 8/200
4/4 [==============================] - 0s 8ms/step - loss: 0.1665 - mean_squared_error: 0.1665
Epoch 9/200
4/4 [==============================] - 0s 8ms/step - loss: 0.1655 - mean_squared_error: 0.1655
Epoch 10/200
4/4 [==============================]

In [13]:
model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_3 (Dense)             (None, 2)                 6         
                                                                 
 dense_4 (Dense)             (None, 1)                 3         
                                                                 
Total params: 9
Trainable params: 9
Non-trainable params: 0
_________________________________________________________________


In [14]:
# Model Prediction
model.predict(np.array([[0,0]]))

2022-05-19 14:20:54.173662: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.


array([[0.48558134]], dtype=float32)

In [15]:
# Model Weights
# <weight, bias> pairs

weights = model.get_weights()
weights

[array([[ 0.10177382,  1.2677077 ],
        [-1.0043843 , -0.1423107 ]], dtype=float32),
 array([ 0.01717393, -0.01435319], dtype=float32),
 array([[-1.384692 ],
        [ 1.5022721]], dtype=float32),
 array([-0.01234779], dtype=float32)]

In [16]:
# Model Visualization

from keras.utils.vis_utils import plot_model
plot_model(model, to_file='model_plot.png', show_shapes=True, show_layer_names=True)

You must install pydot (`pip install pydot`) and install graphviz (see instructions at https://graphviz.gitlab.io/download/) for plot_model/model_to_dot to work.
