# Perceptron

In [1]:
# Reference: https://en.wikipedia.org/wiki/Perceptron

In [2]:
%%latex
$$
\begin{equation}
f(x)=
    \begin{cases}
        1 & \text{if } w \ast x + b >0 \\
        0 & \text{otherwise }
    \end{cases}
\end{equation}
$$

<IPython.core.display.Latex object>

In [3]:
from builtins import int

import numpy as np


def threshold(v: float) -> int:
    return 1 if v >= 0 else 0


class Perceptron:
    def __init__(self, w, b: float):
        self.w = w
        self.b = b

    def update_params(self, w, b):
        self.w = w
        self.b = b

    def predict(self, x) -> int:
        v = np.dot(self.w, x) + self.b
        return threshold(v)


# Hard coded model parameters
def compute_or(x):
    # w1 = 1, w2 = 1, b = -0.5
    w = np.array([1, 1])
    b = -0.5
    return Perceptron(w, b).predict(x)


# Using Perceptron model for OR Logic Gate

test1 = np.array([0, 1])
test2 = np.array([1, 1])
test3 = np.array([0, 0])
test4 = np.array([1, 0])

print("OR({}, {}) = {}".format(0, 1, compute_or(test1)))
print("OR({}, {}) = {}".format(1, 1, compute_or(test2)))
print("OR({}, {}) = {}".format(0, 0, compute_or(test3)))
print("OR({}, {}) = {}".format(1, 0, compute_or(test4)))

OR(0, 1) = 1
OR(1, 1) = 1
OR(0, 0) = 0
OR(1, 0) = 1


# Tensorflow / Keras Library

In [64]:
from keras.layers import Dense
from keras.models import Sequential
X = np.array([[0,0], [0,1], [1,0], [1,1]])
y = np.array([0,1,1,1])
print(X)
print(X.shape)
print(y)

[[0 0]
 [0 1]
 [1 0]
 [1 1]]
(4, 2)
[0 1 1 1]


In [63]:
model = Sequential()
model.add(Dense(1, input_shape=(2,)))

# Designing Model Architecture
# model.add(Dense(1, activation='sigmoid'))
model.compile(optimizer='adam', loss='mse')
model.output_shape

(None, 1)

In [69]:
# Model Training
history = model.fit(X, y, epochs=500, batch_size=1)

Epoch 1/500
4/4 [==============================] - 0s 6ms/step - loss: 0.6825
Epoch 2/500
4/4 [==============================] - 0s 6ms/step - loss: 0.6803
Epoch 3/500
4/4 [==============================] - 0s 6ms/step - loss: 0.6786
Epoch 4/500
4/4 [==============================] - 0s 5ms/step - loss: 0.6753
Epoch 5/500
4/4 [==============================] - 0s 5ms/step - loss: 0.6734
Epoch 6/500
4/4 [==============================] - 0s 6ms/step - loss: 0.6721
Epoch 7/500
4/4 [==============================] - 0s 6ms/step - loss: 0.6691
Epoch 8/500
4/4 [==============================] - 0s 5ms/step - loss: 0.6676
Epoch 9/500
4/4 [==============================] - 0s 6ms/step - loss: 0.6654
Epoch 10/500
4/4 [==============================] - 0s 6ms/step - loss: 0.6635
Epoch 11/500
4/4 [==============================] - 0s 7ms/step - loss: 0.6605
Epoch 12/500
4/4 [==============================] - 0s 6ms/step - loss: 0.6601
Epoch 13/500
4/4 [==============================] - 0s 6ms/st

In [66]:
model.summary()

Model: "sequential_9"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_11 (Dense)            (None, 1)                 3         
                                                                 
Total params: 3
Trainable params: 3
Non-trainable params: 0
_________________________________________________________________


In [76]:
# Model Prediction
model.predict(np.array([[1,1]]))

array([[1.0302854]], dtype=float32)

In [68]:
# Model Weights
# <weight, bias> pairs
weights = model.get_weights()
weights

[array([[ 1.1705086 ],
        [-0.84363055]], dtype=float32),
 array([0.34835762], dtype=float32)]